FROM mesosphere/spark
RUN apt-get update
RUN apt-get install python-pip -y
RUN apt-get install python-dev -y
RUN apt-get install libblas-dev -y
RUN apt-get install liblapack-dev -y
RUN apt-get install gfortran -y
RUN apt-get install libatlas-base-dev -y
RUN apt-get install python-sklearn -y
RUN pip install publicsuffixlist
